// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: clientproto.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace ClientProto {
  public static partial class ClientProto
  {
    static readonly string __ServiceName = "ClientProto.ClientProto";

    static readonly grpc::Marshaller<global::ClientProto.Path> __Marshaller_Path = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ClientProto.Path.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ClientProto.StatusResponse> __Marshaller_StatusResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ClientProto.StatusResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::ClientProto.Path, global::ClientProto.StatusResponse> __Method_DeleteDirectory = new grpc::Method<global::ClientProto.Path, global::ClientProto.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteDirectory",
        __Marshaller_Path,
        __Marshaller_StatusResponse);

    static readonly grpc::Method<global::ClientProto.Path, global::ClientProto.StatusResponse> __Method_AddDirectory = new grpc::Method<global::ClientProto.Path, global::ClientProto.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddDirectory",
        __Marshaller_Path,
        __Marshaller_StatusResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ClientProto.ClientprotoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ClientProto</summary>
    public abstract partial class ClientProtoBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ClientProto.StatusResponse> DeleteDirectory(global::ClientProto.Path request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ClientProto.StatusResponse> AddDirectory(global::ClientProto.Path request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ClientProto</summary>
    public partial class ClientProtoClient : grpc::ClientBase<ClientProtoClient>
    {
      /// <summary>Creates a new client for ClientProto</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ClientProtoClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ClientProto that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ClientProtoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ClientProtoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ClientProtoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ClientProto.StatusResponse DeleteDirectory(global::ClientProto.Path request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteDirectory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ClientProto.StatusResponse DeleteDirectory(global::ClientProto.Path request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteDirectory, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ClientProto.StatusResponse> DeleteDirectoryAsync(global::ClientProto.Path request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteDirectoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ClientProto.StatusResponse> DeleteDirectoryAsync(global::ClientProto.Path request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteDirectory, null, options, request);
      }
      public virtual global::ClientProto.StatusResponse AddDirectory(global::ClientProto.Path request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddDirectory(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ClientProto.StatusResponse AddDirectory(global::ClientProto.Path request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddDirectory, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ClientProto.StatusResponse> AddDirectoryAsync(global::ClientProto.Path request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AddDirectoryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ClientProto.StatusResponse> AddDirectoryAsync(global::ClientProto.Path request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddDirectory, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ClientProtoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ClientProtoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ClientProtoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_DeleteDirectory, serviceImpl.DeleteDirectory)
          .AddMethod(__Method_AddDirectory, serviceImpl.AddDirectory).Build();
    }

  }
}
#endregion
